services:
    alc_entity_rest_client.handler:
        class: ALC\EntityRestClientBundle\Services\RestEntityHandler\RestEntityHandler
        arguments: ["%alc_entity_rest_client%", "@session", "%kernel.bundles%", "@jms_serializer", "@request_stack"]
    alc_entity_rest_client.jms_event_subscriber:
        class: ALC\EntityRestClientBundle\Subscribers\JMSEventSubscriber
        arguments: ["@request_stack","@jms_serializer.object_constructor"]
        tags:
            - { name: 'jms_serializer.event_listener', event: 'serializer.pre_deserialize' }
            - { name: 'jms_serializer.event_listener', event: 'serializer.pre_serialize' }
    alc_entity_rest_client.serializer:
        class: ALC\EntityRestClientBundle\Services\Serializer\Serializer
        arguments:
            - "@request_stack"
            - "@jms_serializer.object_constructor"