services:
    alc_entity_rest_client.handler:
        class: ALC\EntityRestClientBundle\Services\RestEntityHandler\RestEntityHandler
        arguments: ["%alc_entity_rest_client%", "@session", "%kernel.bundles%", "@jms_serializer", "@request_stack"]
    alc_entity_rest_client.jms_pre_deserialize:
        class: ALC\EntityRestClientBundle\Listeners\PreDeserialize
        arguments: ["@request_stack","@jms_serializer.object_constructor"]
        tags:
            - { name: 'jms_serializer.event_listener', event: 'serializer.pre_deserialize' }
